### ISSUE TITLE
Broken on PHP 8.1+

### ISSUE THREAD

**Issue by cweiske** [pear/Net_LDAP2#11]
PHP 8.1 introduced classes for LDAP connections, LDAP results and LDAP result entries.
This breaks Net_LDAP2 because it tries to check for is_resource at some places where objects are returned now, e.g. `Net_LDAP2_Entry::createConnected()`.

This leads to the problem that no result entries are returned anymore.

----
https://www.php.net/ChangeLog-8.php#8.1.0
> LDAP:
> - Convert resource<ldap link> to object \LDAP\Connection.
> - Convert resource<ldap result> to object \LDAP\Result.
> - Convert resource<ldap result entry> to object \LDAP\ResultEntry.

https://www.php.net/manual/en/function.ldap-first-entry.php

**Comment by Neustradamus** [comment]
A PR has been done by @cweiske here:
- https://github.com/pear/Net_LDAP2/pull/13
