### ISSUE TITLE
php-Net-LDAP3

### ISSUE THREAD

**Issue by Neustradamus** [pear/Net_LDAP2#14]
Dear @pear team,

It is possible to add improvements from php-Net-LDAP3?
- https://cgit.kolab.org/php-Net-LDAP3
- https://git.kolab.org/diffusion/PNL/php-net_ldap3
- https://packagist.org/packages/kolab/net_ldap3
- https://www.google.com/search?q=Net+LDAP3

Not up-to-date: https://gitlab.com/roundcube/net_ldap3

**Comment by hbeni** [comment]
See #3

**Comment by Neustradamus** [comment]
@hbeni: Oh sorry, I have forgotten my previous ticket!
