### ISSUE TITLE
Can you import code from Net_LDAP3?

### ISSUE THREAD

**Issue by Neustradamus** [pear/Net_LDAP2#3]
Dear devs,

There is a fork here at 2 places:
- https://gitlab.com/roundcube/net_ldap3
- https://git.kolab.org/diffusion/PNL/

Can you add the code into Net_LDAP2?

Thanks in advance.

**Comment by alecpl** [comment]
This is not a fork, this is a completely different code. It requires Net_LDAP2 for Net_LDAP2_SimpleFileSchemaCache, but other than that it does not have much in common.

**Comment by hbeni** [comment]
If you want certain features, it would be a good practice if you open specific feature rerquests here, describing the feature you want improved/added.
